### PR TITLE
feat: add env for default operator image

### PR DESCRIPTION
**Pull request by jiuker**
feat: add env for default operator image
When operator can't get deployment at first time.
There is no way to set default image for current.
We add a env to set this.

### CODE REVIEW

**Review by shtripat — APPROVED** [review]
lgtm

**Comment by pjuarezd** [comment]
Can you add the env variable to the list in https://github.com/minio/operator/blob/master/docs/env-variables.md please? @jiuker

**Comment by jiuker** [comment]
@pjuarezd ^^

**Review by pjuarezd — APPROVED** [review]

**Review by pjuarezd — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@jiuker PTAL at the conflicts

**Review by harshavardhana — APPROVED** [review]

**Review by pjuarezd — APPROVED** [review]

**Pull request merged**
