### PR TITLE
Tenants will work only with embedded console

### PR DESCRIPTION
**Pull request by dvaldivia**
This PR builds on top of @nitisht PR but has some extra changes, such as:

- Complete removal of the Console Configuration `.spec.console` from the tenant
- `kubectl minio tenant create` now creates a single user for the tenant
- Fixed a problem that was preventing the old console deployment from being deleted
- fixed a problem that was preventing the hot server update to work

**To Test this** make sure to build a new logsearch container image and use that either as the default image or in the tenant's `.spec.log.image` field

### CODE REVIEW

**Comment by ravindk89** [comment]
@dvaldivia minor question - for setting up SSO via Console, I think we'd expect to have to also set `MINIO_BROWSER_REDIRECT_URL` right? Would that be handled in this PR, or would the user be responsible for altering the envvars in the tenant to include that redirect based on the external ingress address?

**Comment by harshavardhana** [comment]
> @dvaldivia minor question - for setting up SSO via Console, I think we'd expect to have to also set `MINIO_BROWSER_REDIRECT_URL` right? Would that be handled in this PR, or would the user be responsible for altering the envvars in the tenant to include that redirect based on the external ingress address?

everything should be handle in this PR - AFAICS @ravindk89

**Comment by ravindk89** [comment]
> > @dvaldivia minor question - for setting up SSO via Console, I think we'd expect to have to also set `MINIO_BROWSER_REDIRECT_URL` right? Would that be handled in this PR, or would the user be responsible for altering the envvars in the tenant to include that redirect based on the external ingress address?
> 
> everything should be handle in this PR - AFAICS @ravindk89

I'll take your word for it, I didn't see the var being set at a glance, but I also don't know all the places to look. I did see we're setting `MINIO_SERVER_URL` so that's good.

**Review by Alevsk — DISMISSED** [review]
I need to test this branch in detail, deploying tenants with oidc, ldap, encryption options, etc, hows is gonna work with console/operator-ui? we will need a new version correct?, ill test all this tonight and tomorrow

**Comment by dvaldivia** [comment]
@ravindk89 @harshavardhana we could have the OIDC callback be set by the browser sine we start the request from there, this would ensure we always can infer the domain regardless of the configuration

**Comment by harshavardhana** [comment]
> @ravindk89 @harshavardhana we could have the OIDC callback be set by the browser sine we start the request from there, this would ensure we always can infer the domain regardless of the configuration

If it's possible that would be great.

**Comment by ravindk89** [comment]
It would certainly simplify a recent pain point if that were the case.

**Review by nitisht — COMMENTED** [review]
Tried updating the Operator image. Here are the steps:

1. Create Operator `v4.1.3` and Tenant with Console enabled.
2. Upgrade Operator to image based on this PR. 

Issues: 
1. Old console pods are not getting deleted/removed.
2. Getting this warning in the Service.

```sh
 Warning  FailedToUpdateEndpointSlices  9m11s  endpoint-slice-controller  Error updating Endpoint Slices for Service default/minio-console: failed to update minio-console-l9vrs EndpointSlice for Service default/minio-console: Operation cannot be fulfilled on endpointslices.discovery.k8s.io "minio-console-l9vrs": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by dvaldivia** [comment]
@nitisht you need to perform a MinIO update to get rid of the console pods

**Comment by nitisht** [comment]
> @nitisht you need to perform a MinIO update to get rid of the console pods

ah right. Let me try that

**Review by nitisht — APPROVED** [review]
LGTM & basic migration scenarios working fine

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
