### PR TITLE
Update golang.org/x/net package

### PR DESCRIPTION
**Pull request by reivaj05**

### CODE REVIEW

**Comment by pjuarezd** [comment]
this is similar, but with a shorter scope than https://github.com/minio/operator/pull/1457

**Comment by reivaj05** [comment]
@pjuarezd I didn't see that other PR, let me check with @cniackz if he can merge his since it's already approved

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by cniackz** [comment]
goreleaser is already passing here and helm fail is unrelated to this change, I like this more as there are few changes here. Let's merge one or the other but at the end we have to fix that vulnerability by updating the module.

**Review by allanrogerr — APPROVED** [review]

**Pull request merged**
