### PR TITLE
Add subnet-utils

### PR DESCRIPTION
**Pull request by reivaj05**
Implements functionality to communicate with SUBNET:

- Login
- Register with API Key
- Retrieve API Key from subnet

This will be used in another PR to register tenants with API key

### CODE REVIEW

**Review by cniackz — DISMISSED** [review]
LGTM

**Review by anjalshireesh — COMMENTED** [review]
Similar code is present in `mc` also. And it is evolving with the evolution of the registration and callhome features. e.g. SUBNET now accepts the `api-key` in the form of a header `x-subnet-api-key` also which is better than passing as query parameter.

Does it make sense to keep these subnet-utils in a common place and use them from both `mc` and `operator` (and `console` also maybe)?

**Comment by reivaj05** [comment]
> Similar code is present in `mc` also. And it is evolving with the evolution of the registration and callhome features. e.g. SUBNET now accepts the `api-key` in the form of a header `x-subnet-api-key` also which is better than passing as query parameter.
> 
> Does it make sense to keep these subnet-utils in a common place and use them from both `mc` and `operator` (and `console` also maybe)?



> Similar code is present in `mc` also. And it is evolving with the evolution of the registration and callhome features. e.g. SUBNET now accepts the `api-key` in the form of a header `x-subnet-api-key` also which is better than passing as query parameter.
> 
> Does it make sense to keep these subnet-utils in a common place and use them from both `mc` and `operator` (and `console` also maybe)?

@anjalshireesh It does, I actually copied a lot from mc repo, and similar code is going to be used in operator repo for kubectl-minio and the operator itself. It would be better if this is in a common place where it can be reusable

cc: @dvaldivia what do you think?

**Comment by reivaj05** [comment]
My branch got corrupted, will fix it and create a new PR for this

**Pull request closed without merging**
