### PR TITLE
Move CRDs to `crds` directory in Helm chart

### PR DESCRIPTION
**Pull request by AlexGodbehere**
This PR moves the `minio.min.io_tenants.yaml` and `sts.min.io_policybindings.yaml` CRDs to the dedicated `/crds` directory within the helm chart

This solves an issue when both the `operator` and `tenant` are used as dependencies in a Helm chart.

See https://github.com/minio/operator/issues/1553 for more information.

### CODE REVIEW

**Comment by dnskr** [comment]
It's also recommended by Helm [documentation](https://helm.sh/docs/topics/charts/#custom-resource-definitions-crds) to keep CRDs in `crds/` directory:

> CRD YAML files should be placed in the crds/ directory inside of a chart.

with example:
```
crontabs/
  Chart.yaml
  crds/
    crontab.yaml
  templates/
    mycrontab.yaml
```

**Comment by shtripat** [comment]
Resolve the conflicts please

**Comment by pjuarezd** [comment]
We'll need to do modify the release scripts as well to apply transformations into the crd directory, will be working on it

**Comment by pjuarezd** [comment]
> We'll need to do modify the release scripts as well to apply transformations into the crd directory, will be working on it

Applied the refactor and tested, after thorough review, move the resources to the `crds` directory will not the path we will follow, see reply on https://github.com/minio/operator/issues/1553#issuecomment-1650661259

**Pull request closed without merging**
