### PR TITLE
Ensure operator changes Tenant state based on requestAutoCert and externalCert fields

### PR DESCRIPTION
**Pull request by nitisht**

### CODE REVIEW

**Comment by Alevsk** [comment]
Current approach to disable external certs is to remove the secrets on the `spec.externalCertSecret` field, why do we need an additional way to disable them 😅 ?

**Comment by harshavardhana** [comment]
what does it mean by toggle? @nitisht can you elaborate a bit. We should discuss this internally on why they need this. As it looks like an unnecessary field and in practice not very useful. 

It doesn't make sense to allow disabling external cert while it was added since the statefulset state change requires entirely removal of external cert anyways. So providing a way to disable/enable is a bit weird.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
@nitisht is this still needed?

**Comment by nitisht** [comment]
need to test the behaviour after #668 will update today

**Comment by nitisht** [comment]
closing as addressed by #668

**Pull request closed without merging**
