### PR TITLE
feat: add sidecar resource to Sidecar container

### PR DESCRIPTION
**Pull request by jiuker**
fix: https://github.com/minio/operator/issues/1543
Add sidecar resource to sidecar to avoid k8s will reject this request which set with namespace quotas
It comes from https://github.com/minio/operator/pull/1734.
Thanks @cniackz

### CODE REVIEW

**Review by cniackz — DISMISSED** [review]
Thank @jiuker for the missing part!

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by cniackz** [comment]
No, thank you @jiuker for fixing this and adding the part that was missing!!!! ❤️

**Review by shtripat — APPROVED** [review]
lgtm

**Review by pjuarezd — APPROVED** [review]

**Pull request merged**
