### PR TITLE
OIDC: remove deprecated variable

### PR DESCRIPTION
**Pull request by cniackz**
### Objectives:

* To remove deprecated var from our example: `MINIO_IDENTITY_OPENID_REDIRECT_URI`
* And also from other spots we located after.

### Related:

* https://github.com/minio/console/issues/2918
* First attempt: https://github.com/minio/operator/pull/1720

### Documentation:

* https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_IDENTITY_OPENID_REDIRECT_URI

### Testing:

1. Tested on existing IDP configuration, it works!.
2. Tested when configured via UI, it works!
3. Tested when configured via CLI, it works!
4. Tested when configured via Tenant Spec, it works!

### CODE REVIEW

**Review by jiuker — CHANGES_REQUESTED** [review]
https://github.com/minio/operator/blob/1557ba0232648067860cb23cd33e9e9eacf65294/api/tenant-add-handlers.go#L463
https://github.com/jiuker/operator/blob/1557ba0232648067860cb23cd33e9e9eacf65294/web-app/src/common/utils.ts#L786
Still have this

**Comment by cniackz** [comment]
Thank you very much @jiuker I will also address those spots and re-test.

**Comment by feorlen** [comment]
A question: does this mean `identity_openid redirect_uri` no longer works either?

https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-config.html#mc-conf.identity_openid.redirect_uri

**Comment by cniackz** [comment]
I have removed more spots. Tests have to pass then I ask for another round of reviews.

**Review by jiuker — APPROVED** [review]
LGTM

**Review by pjuarezd — APPROVED** [review]

**Pull request merged**
