### PR TITLE
feat: add CONSOLE_POLICY key when create user

### PR DESCRIPTION
**Pull request by drivebyer**
close https://github.com/minio/operator/issues/629

### CODE REVIEW

**Comment by dvaldivia** [comment]
I think this is a great idea in general as general improvement to the users being added, perhaps we should also add this to the list of users under `.spec.users` in which case each user can have a separate policy, would that be useful?

Else, my only feedback would be to rename the environment variable to something more aligned with the rest and that indicates this is the default policy, something like `MINIO_OPERATOR_DEFAULT_USER_POLICY`

**Comment by drivebyer** [comment]
> Else, my only feedback would be to rename the environment variable to something more aligned with the rest and that indicates this is the default policy, something like `MINIO_OPERATOR_DEFAULT_USER_POLICY`

On my view, the `CONSOLE_POLICY` is more suitable, becouse it is consistent with `CONSOLE_ACCESS_KEY` and `CONSOLE_SECRET_KEY`

**Comment by dnskr** [comment]
> > Else, my only feedback would be to rename the environment variable to something more aligned with the rest and that indicates this is the default policy, something like `MINIO_OPERATOR_DEFAULT_USER_POLICY`
> 
> On my view, the `CONSOLE_POLICY` is more suitable, becouse it is consistent with `CONSOLE_ACCESS_KEY` and `CONSOLE_SECRET_KEY`

Agree, `CONSOLE_POLICY` aligned with `CONSOLE_ACCESS_KEY` and `CONSOLE_SECRET_KEY`.
Would it be a good idea to use `CONSOLE_POLICY` for now, but deprecate `CONSOLE_*` names for `ACCESS_KEY`, `SECRET_KEY` and `POLICY`?

**Comment by drivebyer** [comment]
> Would it be a good idea to use `CONSOLE_POLICY` for now, but deprecate `CONSOLE_*` names for `ACCESS_KEY`, `SECRET_KEY` and `POLICY`?

Agree. The `CONSOLE_` prefix confuse me a lot on first time.:)

**Pull request closed without merging**
