### PR TITLE
allow to set console env

### PR DESCRIPTION
**Pull request by pitwegner**
This PR allows to set additional environment variables for the console container. For example, this could be used to set the missing `$HOME` variable in case the runtime environment does not set it (see #1337).

### CODE REVIEW

**Review by jiuker — CHANGES_REQUESTED** [review]
it will put like this:
```yaml
          env:

          - name: MINIO_CONSOLE_TLS_ENABLE
            value: "off"
          - name: CLUSTER_DOMAIN
            value: cluster.domain
          - name: WATCHED_NAMESPACE
            value: ""
```

**Review by dnskr — CHANGES_REQUESTED** [review]
The following change fixes the issue.
```yaml
          {{- with .Values.console.env }}
          env: {{- toYaml . | nindent 10 }}
          {{- end }}
```
Also consider to add `env: [ ]` to values.yaml file.

**Comment by dnskr** [comment]
I missed that `nindent` should be `12`, to be the same as indents in operator-deployment.yaml:
```yaml
          {{- with .Values.console.env }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
```

**Comment by pitwegner** [comment]
of course...

**Comment by dnskr** [comment]
LGTM

**Comment by shtripat** [comment]
Please add some description explaining about need/intent for the changes.

**Review by shtripat — APPROVED** [review]
lgtm

**Review by jiuker — APPROVED** [review]

**Review by dnskr — APPROVED** [review]

**Review by pjuarezd — APPROVED** [review]

**Pull request merged**
