### PR TITLE
Allow nil values 'RunAsUser' and 'RunAsGroup' for Openshift 4.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Openshift 4 supports auto-generation RunAsUser and RunAsGroup values. And by default these values a very huge(for example 1000610001) due security reasons. These values are not 1000 like it was for Openshift 3...

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
Some proposed stuff related to https://github.com/minio/operator/pull/1403

**Comment by pjuarezd** [comment]
@allanrogerr PTAL

**Comment by pjuarezd** [comment]
it seems related to the issue @AndrienkoAleksandr https://github.com/minio/operator/pull/1403, actually I found that setting the securityContext and containerSecurityContext the way mentioned in the PR it worked

**Comment by AndrienkoAleksandr** [comment]
ok, I see, to make it working on the Openshift 4, we need to provide in the tenant yaml two empty objects:
```
  pools:
    - servers: 1
      securityContext: {}
      containerSecurityContext: {}
  ```

**Comment by pjuarezd** [comment]
Yes, that way it works, but it shouldn’t need that.
We are still looking at it @AndrienkoAleksandr

**Pull request closed without merging**
