### PR TITLE
default sidecar image to quay.io/minio/operator-sidecar

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by pjuarezd** [comment]
did you published that image already to quay @harshavardhana ?

**Comment by harshavardhana** [comment]
> did you published that image already to quay @harshavardhana ?

Not really, our default must be set to a valid value for the future, any other customization we need we set it via the ENV.

**Review by pjuarezd — APPROVED** [review]

**Review by ramondeklein — APPROVED** [review]
Can we fix this image to a specific version during an official build?

**Comment by pjuarezd** [comment]
> Can we fix this image to a specific version during an official build?

yes @ramondeklein when we do a release we will do

**Pull request merged**
