### PR TITLE
update standard status messages to global variables

### PR DESCRIPTION
**Pull request by soulseen**
Signed-off-by: soulseen <zhuxiaoyang1996@gmail>

### CODE REVIEW

**Comment by soulseen** [comment]
> Why do we need this?

this is for other projects that dependency operator such as [harbor-cluster-operator](https://github.com/goharbor/harbor-cluster-operator#additional-documents), and these messages variables will used in that project, so maybe a good point for other projects.

**Comment by harshavardhana** [comment]
> > Why do we need this?
> 
> this is for other projects that dependency operator such as [harbor-cluster-operator](https://github.com/goharbor/harbor-cluster-operator#additional-documents), and these messages variables will used in that project, so maybe a good point for other projects.

minio-operator was never designed to be importable in this manner @soulseen we need to carefully evaluate this and also even formalize these messages. 

Currently this is not a priority. I would suggest we defer doing these things for now. 

NOTE: minio-operator is also under AGPLv3 License which is incompatible with usage in harbor-cluster-operator

**Comment by soulseen** [comment]
thanks for your response, and I think harbor-cluster-operator as an end-user there have no conflicts, and harbor-cluster-operator is under Apache v2.0 License.

**Comment by harshavardhana** [comment]
Superseded by #272

**Pull request closed without merging**
