### PR TITLE
Add build automation for Helm Chart

### PR DESCRIPTION
**Pull request by cniackz**
The idea I have in mind is to add a test to deploy MinIO Operator using Helm as there is no test for this yet. I might change or update the test accordingly after Daniel's input on this task.

Fixes miniohq/engineering#402

### CODE REVIEW

**Comment by cniackz** [comment]
Ok guys the PR is ready for review, I added a test for Helm deployment of the operator.
There are many changes, because I am trying to reuse the existing functions to install the
operator and install the tenant. But in escense, the idea is the same just using `helm install` command.

**Comment by cniackz** [comment]
Wait for another improvement, I am testing that we can re-use the wait for helm and kustomize when installing the operator... wip

**Review by harshavardhana — COMMENTED** [review]
is this PR ready for review?

**Comment by cniackz** [comment]
Yes, it is ready for review @harshavardhana

**Review by dvaldivia — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
