### PR TITLE
Helm: Adding digest option in Operator image

### PR DESCRIPTION
**Pull request by cniackz**
### Objective:

To support digest in our Operator Helm Image.

### Additional information:

To fix: https://github.com/minio/operator/issues/1599

### How to test:

1. Create a cluster in kind

2. Deploy Operator via Helm with the changes:

* For the operator

```sh
helm install \
     --namespace minio-operator \
     --create-namespace \
     minio-operator ./operator
```

* For the tenant:
 
```sh
helm install \
  --namespace tenant-ns \
  --create-namespace \
  tenant-ns ./tenant
```

### Values to test: 

* Values for `digest`

```yaml
operator:
  image:
    repository: quay.io/minio/operator@sha256
    digest: 28c80b379c75242c6fe793dfbf212f43c602140a0de5ebe3d9c2a3a7b9f9f983
    pullPolicy: IfNotPresent
```

* Values for `tag`

```yaml
operator:
  image:
    repository: quay.io/minio/operator
    tag: v5.0.6
    pullPolicy: IfNotPresent
```

### CODE REVIEW

**Comment by pjuarezd** [comment]
> 

Add these as a  comment in the values.yaml to exemplify how to use the digest format or tag format please @cniackz 

Shouldn't we do this in the `tenant.image` and `kes.image` fields as well as well?

**Comment by cniackz** [comment]
You are right @pjuarezd I will add the example and all other missing images here: Console image, MinIO Image and KES image. Thanks for the feedback and tomorrow I will send new commit to review!

**Review by jiuker — DISMISSED** [review]

**Comment by cniackz** [comment]
Now that changes are complete, I will proceed to test these scenarios and if all looks good, I will request another review from our team.

**Comment by cniackz** [comment]
All manual tests performed for this change has passed:

```
1. Test with console <---------------------------------------------------------- PASS
	1. test with tag <---------------------------------------------------------- PASS
	2. test with digest <------------------------------------------------------- PASS
2. Test minio image on the tenant <--------------------------------------------- PASS
	1. test with tag <---------------------------------------------------------- PASS
	2. test with digest <------------------------------------------------------- PASS
3. test with kes image on tenant <---------------------------------------------- PASS
	1. test with tag <---------------------------------------------------------- PASS
	2. test with digest <------------------------------------------------------- PASS
```

**Comment by cniackz** [comment]
Now waiting to CI/CD tests to complete and if they pass, I will ask for reviews.

**Review by jiuker — APPROVED** [review]

**Review by shtripat — APPROVED** [review]
lgtm. verified with tenant and operator deployment using digest

**Pull request merged**
