### PR TITLE
Add hostNetwork config to Tenant spec

### PR DESCRIPTION
**Pull request by mctoohey**
Allows `hostNetwork: true` to be configured on the tenant pods (https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-and-hostnetwork-pods).

This can be desirable if you want to bypass the Kubernetes network layer and access MinIO more directly.

### CODE REVIEW

**Comment by jiuker** [comment]
Please add minio-port and console-port.

**Comment by mctoohey** [comment]
@jiuker I have pushed a commit that makes the minio and console container ports configurable. This helps avoid port conflicts on the host when using host networking. The services will still expose MinIO and the console on the default ports, same as they did before.

**Review by jiuker — CHANGES_REQUESTED** [review]
Please set with default value and check if they are the same。

**Review by jiuker — CHANGES_REQUESTED** [review]
Please use code to set default and check both.

**Comment by cniackz** [comment]
@mctoohey please help us to resolve conflicts

**Comment by cniackz** [comment]
Matthew, please re-open if needed and do all requested things. It's been since January and there is no input from you.
Thanks!

**Pull request closed without merging**
