### PR TITLE
Add annotations/labels to tenant pods

### PR DESCRIPTION
**Pull request by pauvos**
According to the CRD docs "Pool" supports annotations and labels but the Tenant chart templates don't support them yet.

see Pool CRD: https://github.com/pauvos/operator/blob/master/docs/crd.adoc#pool

The annotations and labels already get picked up by the operator if deployed correctly.

### CODE REVIEW

**Review by dvaldivia — APPROVED** [review]

**Comment by cniackz** [comment]
Ok, `Prometheus` test is failing and the fix is comming: https://github.com/minio/operator/pull/1062

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by seungweonpark** [comment]
I am looking at this PR specially as we need to attach additional network (40Gbps, SRIOV + multus) as dataplane network to accelerate the storage network among pods over multiple nodes. Pod definition to use this resource :

`---
apiVersion: v1
kind: Pod
metadata:
  name: sriov-cni-pod1
  namespace: sriov-network-operator
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-cni-conf1
spec:
  containers:
  - name: sriov-cni-pod1
    image: praqma/network-multitool
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/ens801f0_intelnics_1: '1'
      limits:
        intel.com/ens801f0_intelnics_1: '1'
  nodeName: ar09-09-cyp
---
apiVersion: v1
kind: Pod
metadata:
  name: sriov-cni-pod2
  namespace: sriov-network-operator
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-cni-conf1
spec:
  containers:
  - name: sriov-cni-pod2
    image: praqma/network-multitool
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/ens801f0_intelnics_1: '1'
      limits:
        intel.com/ens801f0_intelnics_1: '1'
  nodeName: ar09-15-cyp`

Wonder if Minio pods allow to use the annotation?:

  **annotations:
    k8s.v1.cni.cncf.io/networks: sriov-cni-conf1**

`---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-cni-conf1
  namespace: sriov-network-operator
spec:
  ipam: |
    {
      "type": "host-local",
      "subnet": "10.56.217.0/24",
      "rangeStart": "10.56.217.100",
      "rangeEnd": "10.56.217.200",
      "routes": [{
        "dst": "0.0.0.0/0"
      }],
      "gateway": "10.56.217.1",
      "dataDir": "/var/lib/cni/networks"
    }
  vlan: 0
  resourceName: ens801f0_intelnics_1
  spoofChk: 'on'
  trust: 'off'
  capabilities: '{ "ips": true }'`

**Comment by seungweonpark** [comment]
I have confirmed that I was able to attach the storage network successfully with this PR. :-)

**Pull request merged**
