### PR TITLE
To fix goreleaser

### PR DESCRIPTION
**Pull request by cniackz**
### Objective:

To fix `goreleaser` test, that's it!

### Additionally use proper flag:

```
  • DEPRECATED: --skip-publish was deprecated in favor of --skip=publish, check https://goreleaser.com/deprecations#-skip for more details
```

### Other files:

Since plugin is not deprecated, these files got updated as well:

* `kubectl-minio/go.mod`
* `kubectl-minio/go.sum`

### CODE REVIEW

**Review by allanrogerr — CHANGES_REQUESTED** [review]
This seems to be accomplishing what https://github.com/minio/operator/pull/2051 is already doing.
Could you check with @dvaldivia to add you goreleaser change?

**Comment by allanrogerr** [comment]
This does not seem necessary @cniackz - see goreleaser run here https://github.com/minio/operator/pull/2051

**Comment by cniackz** [comment]
@allanrogerr, this is unrelated to the 2051 PR. This PR is simply to fix the test, not to deprecate anything. Initially, I thought the plugin was deprecated, but now I see that the PR is still open. We still need this change to fix our CI/CD pipeline. Please review it again.

**Comment by cniackz** [comment]
Thank you anyway for the review @allanrogerr  because it made me realize we never deprecated the plugin 👍

**Review by allanrogerr — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by cniackz** [comment]
Thank you guys ❤️

**Pull request merged**
