### PR TITLE
fix: rename zones->pools with new naming convention

### PR DESCRIPTION
**Pull request by harshavardhana**
We are breaking the CRDs in this one

### CODE REVIEW

**Comment by ravindk89** [comment]
So with [minio/minio#10679](https://github.com/minio/minio/pull/10679) the `minio` server uses "Server Sets" to describe this same concept. 

It's a bit confusing to use 'Pools' in Kubernetes environments, but "Server Sets" in Baremetal. It might be fine in docs as we move forward to separating each into their own island of docs, but I can see it leading to misunderstandings depending on which island a user is coming from.

**Comment by harshavardhana** [comment]
> So with [minio/minio#10679](https://github.com/minio/minio/pull/10679) the `minio` server uses "Server Sets" to describe this same concept.
> 
> It's a bit confusing to use 'Pools' in Kubernetes environments, but "Server Sets" in Baremetal. It might be fine in docs as we move forward to separating each into their own island of docs, but I can see it leading to misunderstandings depending on which island a user is coming from.

Server will also move to Pools - we won't be calling it server sets @ravindk89

**Comment by ravindk89** [comment]
@harshavardhana good to know - I'll look for a PR on that change.

**Comment by harshavardhana** [comment]
@nitisht will send this PR closing

**Pull request closed without merging**
