### PR TITLE
Add new job to test Kubernetes 1.21

### PR DESCRIPTION
**Pull request by dilverse**
Adding new job to test for the last supported version of kubernetes

### CODE REVIEW

**Review by harshavardhana — CHANGES_REQUESTED** [review]
question why on these k8s versions?

**Comment by dilverse** [comment]
Hi @harshavardhana today while testing for the PR #1278 we identified the helm chart update doesn't work with Kubernetes 1.21 version but works with 1.25, since many of the customers still use 1.20 we wanted to ensure we didn't break anything in operator codebase.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana today while testing for the PR #1278 we identified the helm chart update doesn't work with Kubernetes 1.21 version but works with 1.25, since many of the customers still use 1.20 we wanted to ensure we didn't break anything in operator codebase.

So should we simply deprecate helm chart for k8s v1.21 and older ?

**Comment by dvaldivia** [comment]
@harshavardhana after discussing this with Ab, we are going to keep the support for 1.20 around for a little longer, so we should take this in and delay the breaking changes to Helm until k8s 1.26 lands, then we can move our floor to 1.21

**Review by dvaldivia — DISMISSED** [review]

**Comment by dvaldivia** [comment]
We should take this @harshavardhana since we are going to be adding support for container level `SecurityContext` in a backwards compatible way, we need to make sure testing on our floor release is still working. 

Also with the release of `v1.26` we should make `v1.21` the floor release @dilverse

**Comment by dilverse** [comment]
> 

Done bumped the version to 1.21.14

**Review by cniackz — CHANGES_REQUESTED** [review]
Hello Allan, please squash the commits from 4 to 1 and thank you

**Comment by dilverse** [comment]
> Hello Allan, please squash the commits from 4 to 1 and thank you

Why do we need to squash the commits? 
When the PR is getting merged its anyway going to squash and merge right?

**Review by allanrogerr — APPROVED** [review]

**Comment by reivaj05** [comment]
> > Hello Allan, please squash the commits from 4 to 1 and thank you
> 
> Why do we need to squash the commits? When the PR is getting merged its anyway going to squash and merge right?

x2
I know it's a good practice but we are already doing it during merge... why do it twice and dismiss previous approvals?

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by cniackz** [comment]
Ok guys you are right, I haven't think that way but you are right, why do it twice 👍

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
