### PR TITLE
Prepare for the addition of new CRD

### PR DESCRIPTION
**Pull request by cniackz**
### Objective:

This PR has been created in anticipation of introducing a new CRD

### Reason:

Currently, running `./k8s/update-codegen.sh` does not work; it necessitates code changes. If this script is essential for adding new CRDs, it should function properly initially. I suspect that some of the detailed files contain features we no longer support. However, these files were not removed because this script isn't executed frequently enough to automatically generate them.

### CODE REVIEW

**Comment by pjuarezd** [comment]
Could you do `make regen-crd` and `make regen-crd-docs` too @cniackz? just want to make sure CRD and docs are sync with this change

**Review by dvaldivia — CHANGES_REQUESTED** [review]
How were these changed?

**Comment by pjuarezd** [comment]
> How were these changed?

I though these are just because the codegen version was updated recently and all @cniackz did was run `./k8s/update-codegen.sh`

**Comment by dvaldivia** [comment]
if I do that along with `regen-crd` I get also changes to the CRD, @cniackz can you re-run also `regen-crd`?

**Comment by pjuarezd** [comment]
> if I do that along with `regen-crd` I get also changes to the CRD, @cniackz can you re-run also `regen-crd`?

Addressed in last commit, this is fine to merge

**Review by pjuarezd — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
