### PR TITLE
Move UI from console repository to this repository

### PR DESCRIPTION
**Pull request by dvaldivia**
Moving towards single container releases for v5

### CODE REVIEW

**Comment by cniackz** [comment]
My focus here is to look at the test, to fix them accordingly for this PR.

My first task is: I will fix `./web-app/check-warnings.sh` to fix this problem

```
./web-app/check-warnings.sh:16:8: note: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead. [SC2002]
```

**Comment by cniackz** [comment]
First change is going to be:

```
Cesars-MacBook-Pro:operator cniackz$ gst
On branch operator-ui
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   web-app/check-warnings.sh

no changes added to commit (use "git add" and/or "git commit -a")
Cesars-MacBook-Pro:operator cniackz$ git diff .
diff --git a/web-app/check-warnings.sh b/web-app/check-warnings.sh
index 2c6e7121..9013400d 100755
--- a/web-app/check-warnings.sh
+++ b/web-app/check-warnings.sh
@@ -13,7 +13,7 @@ try() { "$@" &> yarn.log || die "cannot $*"; }
 rm -f yarn.log
 try make build-static
 
-if cat yarn.log | grep "Compiled with warnings"; then
+if grep "Compiled with warnings" yarn.log; then
   echo "There are warnings in the code"
   exit 1
 fi
Cesars-MacBook-Pro:operator cniackz$ 
```

**Comment by cniackz** [comment]
@dvaldivia when you get a chance, please take a look at this PRs:

1. https://github.com/dvaldivia/operator/pull/3
2. https://github.com/dvaldivia/operator/pull/4

As I will keep adding more to fix the tests.

**Comment by cniackz** [comment]
@dvaldivia please take a look at:

https://github.com/dvaldivia/operator/pull/9

It will fix coverage test as below:

https://github.com/minio/operator/actions/runs/4314052180

image

**Review by bexsoft — APPROVED** [review]
LGTM

Steps to init server:
1. Start Operator server `go run . ui`
2. Install Yarn packages in web-app
3. Run yarn start in web-app folder

**Review by pjuarezd — APPROVED** [review]

**Pull request merged**
