### PR TITLE
Release v4.4.22

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

Additionally Helm test got improved in this PR plus changes added for the new release.

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Review by cniackz — DISMISSED** [review]
LGTM

**Comment by cniackz** [comment]
Re ran `Add build automation for Helm Chart`

**Comment by cniackz** [comment]
2nd failure: https://github.com/minio/operator/runs/6625769871?check_suite_focus=true
Wonder if we introduce an issue here...

**Comment by cniackz** [comment]
Third failure of `Add build automation for Helm Chart` I will start debugging in a bit.
I would like to have this test passing prior merging this release...

**Comment by cniackz** [comment]
@dvaldivia added fix:

```sh
$ git diff testing/common.sh
diff --git a/testing/common.sh b/testing/common.sh
index b89b65c..b41c3d9 100644
--- a/testing/common.sh
+++ b/testing/common.sh
@@ -54,6 +54,10 @@ function install_operator() {
   echo 'end - load compiled image so we can use it later on'
 
   if [ "$1" = "helm" ]; then
+
+    echo "Change the version accordingly for image to be found within the cluster"
+    yq -i '.operator.image.tag = "dev"' "${SCRIPT_DIR}/../helm/operator/values.yaml"
+
     echo "Installing Current Operator via HELM"
     helm install \
       --namespace minio-operator \
```

**Comment by cniackz** [comment]
Wait one more fix:

```sh
$ git diff testing/common.sh
diff --git a/testing/common.sh b/testing/common.sh
index b41c3d9..f95728c 100644
--- a/testing/common.sh
+++ b/testing/common.sh
@@ -179,7 +179,7 @@ function install_tenant() {
     namespace=default
     key=app
     value=minio
-    helm install --namespace tenant-ns \
+    helm install --namespace $namespace \
       --create-namespace tenant ./helm/tenant
   else
     namespace=tenant-lite
```

This is to have the tenant in `default` namespace as expected by validation.

**Comment by cniackz** [comment]
One last fix:

```sh
$ git diff testing/common.sh
diff --git a/testing/common.sh b/testing/common.sh
index f95728c..a3e5d41 100644
--- a/testing/common.sh
+++ b/testing/common.sh
@@ -176,6 +176,10 @@ function install_tenant() {
 
   echo "Check if helm will install the Tenant"
   if [ "$1" = "helm" ]; then
+
+    echo "This test is intended for helm only not for KES, there is another kes test, so let's remove KES here"
+    yq -i eval 'del(.tenant.kes)' "${SCRIPT_DIR}/../helm/tenant/values.yaml"
+
     namespace=default
     key=app
     value=minio
```

This is for pod tenants to be ready without KES, remember there is a special test for KES, so let's avoid mixing complex scenarios here, all we want is Helm testing.

**Comment by cniackz** [comment]
Manual testing performed locally with these steps: https://github.com/cniackz/minio/wiki/automation-for-helm-chart

**Review by cniackz — APPROVED** [review]
LGTM

**Review by Alevsk — APPROVED** [review]

**Pull request merged**
