### PR TITLE
Split Update Logic to separate file

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by Alevsk — DISMISSED** [review]

**Comment by harshavardhana** [comment]
PTAL at the conflicts @dvaldivia

**Comment by dvaldivia** [comment]
done @harshavardhana

**Comment by harshavardhana** [comment]
Looks like this is not needed anymore? @dvaldivia

**Comment by dvaldivia** [comment]
it is needed to simplify `main-controller.go` @harshavardhana , I just wanted to make it on a separate PR, but I cam send this one the next PR

**Pull request closed without merging**
