### PR TITLE
fix: delete csr when tenant has been deleted

### PR DESCRIPTION
**Pull request by jiuker**
fix https://github.com/minio/operator/issues/1843
Once the tenant is deleted, the deletion progress should be removed it.

### CODE REVIEW

**Review by harshavardhana — DISMISSED** [review]

**Review by shtripat — APPROVED** [review]
LGTM. Verified.

**Review by dvaldivia — CHANGES_REQUESTED** [review]
This will attempt to delete it on every sync, which would be unproductive, if the idea is to delete the CSR when the tenant is deleted, just declare the tenant as the owner of the CSR

**Comment by shtripat** [comment]
> This will attempt to delete it on every sync, which would be unproductive, if the idea is to delete the CSR when the tenant is deleted, just declare the tenant as the owner of the CSR

Initially it was like
```
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  creationTimestamp: "2023-11-13T06:10:10Z"
  labels:
    v1.min.io/tenant: tenant1
  name: tenant1-tenant-ns-csr
  ownerReferences:
  - apiVersion: minio.min.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: tenant1
    uid: a9e2f5b2-7314-42b2-937b-a0658cbb5001
```
but it was not getting deleted after tenant deletion.

**Comment by jiuker** [comment]
> This will attempt to delete it on every sync, which would be unproductive, if the idea is to delete the CSR when the tenant is deleted, just declare the tenant as the owner of the CSR

```go
	// Get the Tenant resource with this namespace/name
	tenant, err := c.minioClientSet.MinioV2().Tenants(namespace).Get(context.Background(), tenantName, metav1.GetOptions{})
	if err != nil {
		// The Tenant resource may no longer exist, in which case we stop processing.
		if k8serrors.IsNotFound(err) {
```
 Not every sync. And `declare the tenant as the owner of the CSR` is not ok for that. @shtripat and me have tried that. @dvaldivia

**Comment by pjuarezd** [comment]
> > This will attempt to delete it on every sync, which would be unproductive, if the idea is to delete the CSR when the tenant is deleted, just declare the tenant as the owner of the CSR
> 
> ```go
> 	// Get the Tenant resource with this namespace/name
> 	tenant, err := c.minioClientSet.MinioV2().Tenants(namespace).Get(context.Background(), tenantName, metav1.GetOptions{})
> 	if err != nil {
> 		// The Tenant resource may no longer exist, in which case we stop processing.
> 		if k8serrors.IsNotFound(err) {
> ```
> 
> Not every sync. And `declare the tenant as the owner of the CSR` is not ok for that. @shtripat and me have tried that. @dvaldivia

Well, this is interesting, I think is worth investigate why the CSR is not being removed altogether with the Tenant.

On the other hand, this will not work, `syncHandler` could be invoked before the Operator requests a CSR renewal or the CSR is approved or the certificate is issued, messing up the certificates renewal flow.

We check the presence of the certificate in the CSR to determine if need to delete it and recreate it.
https://github.com/minio/operator/blob/251516243bf0647e8990303f01fe342de6730a03/pkg/controller/minio.go#L230-L259

Anyways Kubernetes deletes CSR's a few hours after cert is issued.

Why is the CSR not deleted explicitly a problem?

**Comment by jiuker** [comment]
> Anyways Kubernetes deletes CSR's a few hours after cert is issued.
> 
> Why is the CSR not deleted explicitly a problem?

Not sure if K8S has any special handling for this. This csr deletion will only be triggered after tenant deletion. @pjuarezd

**Pull request closed without merging**
