### PR TITLE
Release v4.4.14

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by harshavardhana — APPROVED** [review]

**Comment by dnskr** [comment]
Is it ok that there is no v4.4.13 version?

**Comment by harshavardhana** [comment]
actually we can do v4.4.13 @dvaldivia

**Comment by dvaldivia** [comment]
I did a phony `v4.4.13` that was never released :P  so I figured to skip it and go to 4.4.14 to make sure I'm not missing anything, should we revive that?

**Comment by harshavardhana** [comment]
> I did a phony `v4.4.13` that was never released :P  so I figured to skip it and go to 4.4.14 to make sure I'm not missing anything, should we revive that?

Yes @dvaldivia

**Pull request closed without merging**
