### PR TITLE
fix `kubectl minio init -o`

### PR DESCRIPTION
**Pull request by rustysys-dev**
fix https://github.com/minio/operator/issues/358 by adding respective APIVersion/Kind to generated resources.

### CODE REVIEW

**Review by nitisht — APPROVED** [review]
LGTM, Thanks for the PR @rustysys-dev

**Comment by rustysys-dev** [comment]
@nitisht Glad I can be of help!  When do you suppose this would make it into the next krew release?

**Comment by nitisht** [comment]
Difficult to put a date, but we'll get this merged and it should be available soon.

**Comment by rustysys-dev** [comment]
> Difficult to put a date, but we'll get this merged and it should be available soon.

Got it! thanks again! I will wait for the release!

**Review by Praveenrajmani — APPROVED** [review]

**Pull request merged**
