### PR TITLE
Tenant chart: : add extra resources capability

### PR DESCRIPTION
**Pull request by IxDay**
This commit introduces an extraResources value which is directly rendered as part of the chart like a regular Helm template. This allows users to add some Kubernetes object they might need as part of their cluster configuration.
I added in the comment an example of my use case because I use a different type of ingress and it is easier to configure it this way.

Closes: #1642

### CODE REVIEW

**Review by jiuker — CHANGES_REQUESTED** [review]
This seems to be a solution to a certain need. It does not fall into any of the following categories:
1. bugfix
2. enhancements
3.feature
4.cleanup

**Comment by harshavardhana** [comment]
what does this really do? @IxDay

**Comment by IxDay** [comment]
This allows to ship additional resources with your Helm chart deployment. For instance, I need to deploy an external secret and a different ingress type alongside the minio regular resources. This is dependent on my current config and I think the goal of the Helm chart is not to support every CRD or custom configuration.
The bitnami community came out with a nice solution to this by providing a way to inject additional kubernetes objects with the Helm chart currently deployed. This is this solution I implemented here.
You can then put in your `values.yaml` file:

```yaml
extraResources:
  - |
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: {{ dig "secrets" "name" "" (.Values | merge (dict)) }}
    spec:
      secretStoreRef:
        name: {{ dig "secrets" "name" "" (.Values | merge (dict)) }}
        kind: SecretStore
      refreshInterval: "0"
      target:
        creationPolicy: Merge
        deletionPolicy: Retain
        template:
          data:
            config.env: |-
              export MINIO_ROOT_USER='{{ printf "{{.user}}" }}'
              export MINIO_ROOT_PASSWORD='{{ printf "{{.password}}" }}'
      dataFrom:
      - extract:
          key: secret/minio/{{.Values.tenant.serviceAccountName}}/creds
          conversionStrategy: Default
          decodingStrategy: Auto
```

And it will deploy the additional resource using the same helpers and values from the Helm chart

**Comment by jiuker** [comment]
I think here is a hack of the entrance, I personally feel that if there is helm lack of resources you must, the scenario is universal, I think this is the kind of scenario we need to consider. If this portal is open, I think for us to gain limited. What do you think about this? @harshavardhana

**Review by jiuker — APPROVED** [review]

**Review by pjuarezd — APPROVED** [review]

**Pull request merged**
