### PR TITLE
Remove fullname from helm chart since nothing uses it

### PR DESCRIPTION
**Pull request by dvaldivia**

### CODE REVIEW

**Review by ramondeklein — APPROVED** [review]

**Review by ramondeklein — CHANGES_REQUESTED** [review]
I checked the code if we really need this name to be fixed, but there are not a lot of places where we need this name to be fixed. The `controller.getOperatorDeploymentName()` function looks like this ([source](https://github.com/minio/operator/blob/54be9cb887c77d6f5279fe204e1a496a0f925e97/pkg/controller/operator.go#L308-L311)):
```go
func getOperatorDeploymentName() string {
        // NOTE: constants expanded for clarity in this PR
	return env.Get("MINIO_OPERATOR_DEPLOYMENT_NAME", "minio-operator")
}
```
I don't think this name needs to be fixed, if we also set the `MINIO_OPERATOR_DEPLOYMENT_NAME` environment variable properly and set the name [here](https://github.com/minio/operator/blob/54be9cb887c77d6f5279fe204e1a496a0f925e97/helm/operator/templates/operator-deployment.yaml#L4). According to the [documentation](https://min.io/docs/minio/kubernetes/openshift/reference/operator-environment-variables.html#envvar.MINIO_OPERATOR_DEPLOYMENT_NAME) this is a support scenario (that probably doesn't work properly anymore for a while). It should be tested though.

It's fine by me to hardcode the name, but then we should remove this environment variable from code and update the documentation too.

**Review by shtripat — APPROVED** [review]

**Comment by harshavardhana** [comment]
> ```go
> func getOperatorDeploymentName() string {
>         // NOTE: constants expanded for clarity in this PR
> 	return env.Get("MINIO_OPERATOR_DEPLOYMENT_NAME", "minio-operator")
> }
> ```

@dvaldivia ^^

**Review by pjuarezd — APPROVED** [review]

**Comment by ramondeklein** [comment]
@dvaldivia I think we should remove the environment variable if we decide to use a fixed name. That's why I didn't approve this change. I'ld be happy to remove this variable in this PR...

**Comment by harshavardhana** [comment]
> @dvaldivia I think we should remove the environment variable if we decide to use a fixed name. That's why I didn't approve this change. I'ld be happy to remove this variable in this PR...

@ramondeklein please send it separately, this PR can be merged as is.

**Pull request merged**
