### PR TITLE
Release 6.0.0

### PR DESCRIPTION
**Pull request by pjuarezd**
Release 6.0.0

```
make release RELEASE_SIDECAR=true RELEASE=6.0.0
```

### CODE REVIEW

**Review by harshavardhana — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Comment by pjuarezd** [comment]
`test-cert-manager` is broken, will fix in another PR

**Comment by harshavardhana** [comment]
> `test-cert-manager` is broken, will fix in another PR

so we can merge this? @pjuarezd

**Comment by pjuarezd** [comment]
> > `test-cert-manager` is broken, will fix in another PR
> 
> so we can merge this? @pjuarezd

not yet

**Comment by pjuarezd** [comment]
Failing test is fixed on https://github.com/minio/operator/pull/2220

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
