### PR TITLE
add --console-image flag to kubectl-minio

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
This is a bit of a brutal approach of just clobbering the first container.  I'm a bit ignorant... is the an elegant way of finding the container spec by name?

**Comment by dvaldivia** [comment]
@jhoblitt I mean, we only spec one container in that pod, so it should be fine, I'm starting to think we should avoid code duplication on the plugin and have it load the kustomize logic from go just like the kubeflow `kfctl` command does

**Review by dvaldivia — APPROVED** [review]

**Comment by jhoblitt** [comment]
@dvaldivia I agree that having duplicate logic and flat files is going to lead to grief.  Using the yaml files as a source of truth sounds like a very good idea to me but I've never seen that before.

**Comment by dvaldivia** [comment]
@jhoblitt I'm sure it's doable since other `ctl` style plugins follow that pattern, that's what I tried when I bundled the yamls with the plugin and loaded them dynamically, the problem is we are only creating the resources, no applying them, so we are going to get a bunch of warnings/problems upgrading this resources in the future

**Comment by jhoblitt** [comment]
This sounds like a possible use case for embed if it possible to upgrade to 1.16.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
