### PR TITLE
remove minioJob

### PR DESCRIPTION
**Pull request by jiuker**
remove minioJob

### CODE REVIEW

**Comment by pjuarezd** [comment]
> remove minioJob

@ramondeklein @dvaldivia @jiuker @harshavardhana  a bit of info on why this feature is being remove would be helpful

**Comment by ramondeklein** [comment]
@pjuarezd I think it's considered an enterprise feature.

**Review by ramondeklein — APPROVED** [review]

**Review by pjuarezd — APPROVED** [review]

**Comment by nicolasps-wisemodo** [comment]
I just wanted to mention, I installed the operator from scratch using the main branch, using the default values.yaml file, with terrible results. The operator was no longer functional, tenants were not being created.

On the operator's logs, the following errors appeared several times present:

`failed to watch *v1alpha1.miniojob: failed to list *v1alpha1.miniojob: the server could not find the requested resource (get miniojobs.job.min.io)
`

`waiting for the sts certificates secret to be issued`

Initially, I thought it was some kind of RBAC issue causing the error, but then I realized the MinioJob CRD was missing. I looked for the missing CRD in version v6.0.4 (https://github.com/minio/operator/blob/v6.0.4/helm/operator/templates/job.min.io_jobs.yaml) and copied it into `operator/helm/operator/templates/`, and after restarting the operator's pod, everything worked as expected. The error messages disappeared from the log, and for the first time the tenant was created.

**Comment by ramondeklein** [comment]
@nicolasps-wisemodo Please use tagged releases.

**Comment by nicolasps-wisemodo** [comment]
No doubt I will @ramondeklein

**Comment by dharmil** [comment]
Does this mean the future versions won't support MinIOJob? That kind of contradicts the advice given in https://github.com/minio/operator/issues/1100

**Comment by Syndlex** [comment]
I understand that we don’t have entitlement to specific features.

However, I believe this is a crucial feature for any Minio deployment, regardless of the use case. While it's possible to implement a workaround, it's not particularly difficult, which may reduce the incentive to move to the Enterprise version.

For smaller companies or opensource projects, creating these workarounds can be time-consuming, and there are already several options available, such as #1100, [InseeFrLab S3 Operator](https://github.com/InseeFrLab/s3-operator), creating a Kubernetes Job, using Helm hooks or ArgoCD hooks.

Could you kindly provide some clarity on why this feature is categorized as an Enterprise feature?

**Comment by ramondeklein** [comment]
We have evaluated `MinioJob` and there are a few issues with it.

The community actually requests a fully declarative way (so `MinioBucket`, `MinioUser`, `MinioPolicy`, ... CRDs). We have evaluated this idea, but we need to create an almost endless amount of CRDs to match the S3 API. Re-using `mc` was way simpler. When we would have created a CRD-based approach, then others would probably ask for a Hashicorp Terraform provider. It's a rabit hole...

Each functionality requires development, but that's not all. We need to maintain, document and also support it. There are other projects that do supply such functionality (like https://github.com/InseeFrLab/s3-operator). We think we should focus on what is important. Adding all kind of niche-features distracts us from doing the most important part, building an high-performance, scalable and reliable object store.

For these reasons we have decided to remove this feature. There are other methods that can be used to initiate MinIO jobs (like spinning up an `mc` job yourself) or you can use alternative methods.

**Comment by ElanHasson** [comment]
This is pretty frustrating as this is something being relied upon. 

I'm now in a position where I have to implement all of this existing functionality by myself.

It would have been great to have a deprecation announcement and also not introducing a breaking change in what many would consider a patch release.

**Pull request merged**
