### PR TITLE
Add Ingress for operator console

### PR DESCRIPTION
**Pull request by dnskr**
This PR adds Ingress for operator console. It is optional and disabled by default.
Related to [issue#585](https://github.com/minio/operator/issues/585)

### CODE REVIEW

**Comment by Hokwang** [comment]
@harshavardhana @Alevsk  @nitisht please review this.

**Comment by Hokwang** [comment]
@dnskr please consider k8s version under 1.18

**Comment by sergeyshaykhullin** [comment]
@dnskr Can you please find some time to change Ingress template? 🙏

**Comment by sergeyshaykhullin** [comment]
:green_heart:

**Comment by dnskr** [comment]
@Hokwang @sergeyshaykhullin I have test it on minikube with different versions of kubernetes, but could you please double check it if possible?

**Comment by sergeyshaykhullin** [comment]
`helm template test-release -n test-namespace -f values.yaml . > templated.yaml`

```yaml
# Source: minio-operator/templates/console-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-release-console
  namespace: test-namespace
spec:
  rules:
    - host: console.local
      http:
        paths:
          - path: /
            backend:
              serviceName: "console"
              servicePort: http
```

```
kubectl get ing -n test-namespace
NAME                   CLASS    HOSTS           ADDRESS        PORTS   AGE
test-release-console   <none>   console.local   10.99.13.135   80      16s
```

Seems like it is valid, i will check it as it will merged with production values

**Comment by sergeyshaykhullin** [comment]
Also i think that to have an ability to add ingress per-tenant with native minio ui is also good

Any drawbacks to do so?

I can implement this is a separate pr

**Comment by dnskr** [comment]
Each minio tenant can have 2 Ingress objects: one for tenant console and one for object storage ui.
I'm not sure how they should be implemented. There are 2 options I see and the second one is preferable from my point of view:
1. add to helm chart
2. add to Tenant CRD

We should ask project maintainers/owners for this question.

**Comment by dnskr** [comment]
@harshavardhana @nitisht @dvaldivia  Could you please provide some comments why this shouldn't or couldn't be merged?

**Comment by harshavardhana** [comment]
> @harshavardhana @nitisht @dvaldivia  Could you please provide some comments why this shouldn't or couldn't be merged?

This can be taken, I don't see any issues as such. Need to test it once..

**Comment by dnskr** [comment]
Hi @harshavardhana! Could you please help to proceed with this PR?

**Review by nitisht — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
