### PR TITLE
Remove namespace create/delete privileges from Operator

### LINKED ISSUE #441: Can we reduce the required CustomResourceDefinitions permissions to run the MinIO operator?
**Is your feature request related to a problem? Please describe.**
I am trying to deploy to a shared cluster and I _really_ don't feel comfortable creating a role that can delete entire namespaces or collections. Not only is it scary from a development standpoint, but it's also difficult to administrate. We intentionally locked down each user account's ability to create CRDs and now MinIO is forcing us to give one developer full-admin privileges just to get it up and running. For example, why does it need namespace creation and deletion privileges? It already expects namespaces to exist for tenants. Lets just error out if the namespace doesn't exist? Stuff like that seems heavy handed. I'm waiting for the day someone manages to delete an entirely unrelated namespace under the wrong CRD.  

**Describe the solution you'd like**
To be honest, the less CRDs required to deploy, the easier. They might make your application easier to think about from your end, but they add another layer of complexity. I'd really prefer raw K8 deployments, but I understand that's a much bigger ask. 

**Describe alternatives you've considered**
Alternatively, just limit the scope of these actions. Maybe only _create_ and not _delete_? Lets just force an admin to remove tenants rather than giving a dev the tool to create or delete anything?

### PR DESCRIPTION
**Pull request by nitisht**
Also do not automatically create namespaces in
Operator plugin

Fixes #441

### CODE REVIEW

**Comment by dvaldivia** [comment]
Still need to remove `namespace` from the `cluster-role.yaml` on line 32 (of the pr version)

**Comment by nitisht** [comment]
> Still need to remove `namespace` from the `cluster-role.yaml` on line 32 (of the pr version)

Great catch, thank you. Removed.

**Review by harshavardhana — APPROVED** [review]

**Comment by harshavardhana** [comment]
PTAL @Praveenrajmani @Alevsk @kerneltime @dvaldivia

**Review by Praveenrajmani — APPROVED** [review]
LGTM

**Pull request merged**
