### PR TITLE
applyconfiguration generated objects

### PR DESCRIPTION
**Pull request by pjuarezd**
To fix: https://github.com/minio/operator/issues/1388

### CODE REVIEW

**Comment by dvaldivia** [comment]
is this code generated automatically on release 0.27.0 or do we need any additional flags?

**Comment by pjuarezd** [comment]
> is this code generated automatically on release 0.27.0 or do we need any additional flags?

`0.27.0-alpha.2`, no additional flag, the "all" flag is enough to include the applyconfiguration objects in this version.
https://github.com/minio/operator/blob/6c2cb23eef73accb43a155f56915f73373eafd93/k8s/update-codegen.sh#L43

**Review by dvaldivia — APPROVED** [review]

**Comment by cniackz** [comment]
test-kes failure is not associate with this change I think, so we can consider all tests as passing!

**Review by cniackz — APPROVED** [review]
Nice Job @pjuarezd thank you for the fix!

**Review by allanrogerr — COMMENTED** [review]
Pulled and tested locally!

**Pull request merged**
