### PR TITLE
Remove MINIO_IDENTITY_OPENID_REDIRECT_URI - Deprecated

### PR DESCRIPTION
**Pull request by cniackz**
### Objective:

To remove deprecated var from our example: `MINIO_IDENTITY_OPENID_REDIRECT_URI `

### Related:

* https://github.com/minio/console/issues/2918

### Documentation:

* https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_IDENTITY_OPENID_REDIRECT_URI

### CODE REVIEW

**Review by cesnietor — COMMENTED** [review]
how is it deprecated?
I still see it being used in the code:
https://github.com/minio/operator/blob/master/api/tenant-handlers.go#L409

**Comment by cniackz** [comment]
@feorlen it is in the documentation: https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_IDENTITY_OPENID_REDIRECT_URI the idea is to remove all legacy things as this var is no longer needed for the configuration.

**Comment by feorlen** [comment]
> remove all legacy things as this var is no longer needed for the configuration.

If `MINIO_BROWSER_REDIRECT_URL` is a direct replacement for the deprecated `MINIO_IDENTITY_OPENID_REDIRECT_URI` might be nice to include it in the example. (But not if the new envvar does something very different.)

Or perhaps it isn't a regularly needed option anyway. One thing we do in the docs is make examples with all the possible things you can set, then say "minimum required: A, B, C." Something to consider.

**Comment by cniackz** [comment]
Yes @feorlen that sounds good to me. In the meantime, the best example I can think of is: https://github.com/minio/wiki/wiki/How-to-test-MinIO-SSO-keycloak

**Comment by cniackz** [comment]
Hello @cesnietor it is deprecated because console is adding this for us:

```
./pkg/auth/idp/oauth2/provider.go:	redirectURL := scheme + "://" + r.Host + "/oauth_callback"
```

So we no longer need to provide this deprecated variable anymore.

But anyway you are right, I was missing other spots. I am changing those but I need to test them prior another review.

**Comment by cniackz** [comment]
I will follow in https://github.com/minio/operator/pull/1722

**Pull request closed without merging**
