### PR TITLE
Cleanup and install missing build dependencies

### PR DESCRIPTION
**Pull request by balamurugana**
Signed-off-by: Bala.FA <bala@minio.io>

### CODE REVIEW

**Comment by balamurugana** [comment]
It seems Github workflow failure is not related by changes in this PR. Refer https://github.com/minio/operator/pull/1432

**Comment by cniackz** [comment]
@balamurugana please resolve the conflict.

**Comment by cniackz** [comment]
@balamurugana also would be nice if you add a description and explain a bit more on the advantages of this PR. That might help us understand better if we are missing something to understand from the code.

**Comment by balamurugana** [comment]
> @balamurugana also would be nice if you add a description and explain a bit more on the advantages of this PR. That might help us understand better if we are missing something to understand from the code.

@cniackz As mentioned in the title, this is just a Makefile cleanup with restructuring targets. As notable target change is `docker` to `docker-build`

**Comment by pjuarezd** [comment]
I see what you did here, makes sense, we really have no need to run individually each of these steps  as actions as they are ran anyways on any test, those are only wasting github actions:

```
       - logsearch
       - operator
       - lint
       - gotest
       - getdeps
       - govet
```

sorry I did not check it before and now it's on a conflict state, would you mind solve the conflicts please @balamurugana?

**Comment by pjuarezd** [comment]
Closing this PR, this PR https://github.com/minio/operator/pull/1507 one does something similar

**Pull request closed without merging**
