### PR TITLE
Add ingresses to tenant helm chart

### PR DESCRIPTION
**Pull request by dnskr**
PR implements https://github.com/minio/operator/issues/585 with some additional improvements.

### Implementation notes:
- Two independent Ingress objects have been added to tenant helm chart: `API Ingress` and `Console Ingress`
- Operator Ingress has been simplified due to minimal Kubernetes version requirement
- MinIO version has been updated in tenant helm chart
- Fixed some value types in tenant helm chart

### Testing notes:
Tested locally on minikube
```
$ minikube start
$ minikube addons enable ingress
$ minikube version
minikube version: v1.25.2
```
Tested by deploying without TLS
```
helm install minio-tenant tenant \
 --set tenant.pools[0].volumesPerServer=1 \
 --set tenant.certificate.requestAutoCert=false \
 --set tenant.kes.kesSecret.name="" \
 --set tenant.prometheus.diskCapacityGB="" \
 --set tenant.log.audit.diskCapacityGB="" \
 --set ingress.api.enabled=true \
 --set ingress.console.enabled=true \
 --namespace minio-tenant --create-namespace
```
API check
```
$ mc alias set minio http://minio.local minio minio123
Added `minio` successfully.
$ mc ls minio
[2022-05-26 15:44:44 CEST]     0B test/
```
Console check
tenant-login
tenant-console

### CODE REVIEW

**Comment by dnskr** [comment]
Tested by deploying with auto TLS enabled in MinIO - `tenant.certificate.requestAutoCert=true`
```
helm install minio-tenant tenant \
 --set tenant.pools[0].volumesPerServer=1 \
 --set tenant.certificate.requestAutoCert=true \
 --set tenant.kes.kesSecret.name="" \
 --set tenant.prometheus.diskCapacityGB="" \
 --set tenant.log.audit.diskCapacityGB="" \
 --set ingress.api.enabled=true \
 --set ingress.api.annotations."nginx\.ingress\.kubernetes\.io\/backend\-protocol"=HTTPS \
 --set ingress.console.enabled=true \
 --set ingress.console.annotations."nginx\.ingress\.kubernetes\.io\/backend\-protocol"=HTTPS \
 --namespace minio-tenant --create-namespace
```
API check
```
$ mc alias set minio http://minio.local minio minio123
Added `minio` successfully.
$ mc ls minio
[2022-05-27 20:01:57 CEST]     0B test/
```
Console check
tenant-login-https
tenant-console-https

**Comment by cniackz** [comment]
We currently have version 4.4.22 in progress with changes for helm test already, let's get this version merged then I will understand and test this requested change. Thank you @dnskr for this PR! 👍

**Comment by dnskr** [comment]
The PR has been rebased onto [Release v4.4.22](https://github.com/minio/operator/commit/24189e106ad67c6c4ba0ad7f54dd0bc5190ef11e) commit in master.

**Comment by cniackz** [comment]
Tested manually and tenant can be deployed:

Screen Shot 2022-05-30 at 2 22 27 PM

**Review by cniackz — APPROVED** [review]
It looks good to me:

1. All tests are passing (not affected)
2. Tenant can be deployed via Helm (Either kind or minikube)
3. It is a nice addition to have load balancer (ingress controller)

**Comment by cniackz** [comment]
Hello @dnskr yes, I have removed the `wip` label 👍 and added more people to review this PR.

**Review by Alevsk — APPROVED** [review]

**Comment by ViokingTung** [comment]
I have a suggestion: when we  enabled ingress, the default max file size must be less 1M, so can we add a config like `nginx.org/client-max-body-size: "4096m"`

**Pull request merged**
