### PR TITLE
Release 5.0.12

### PR DESCRIPTION
**Pull request by pjuarezd**

### CODE REVIEW

**Review by cniackz — APPROVED** [review]

**Review by reivaj05 — APPROVED** [review]

**Comment by jplimack** [comment]
@pjuarezd @cniackz @reivaj05 there is no `v5.0.12` in the quay.io registry, so this broke consumers of the helm chart
```
 crane ls quay.io/minio/operator | grep v5.0.1  
v5.0.1-amd64
v5.0.1-ppc64le
v5.0.1-s390x
v5.0.1-arm64
v5.0.1
v5.0.10-amd64
v5.0.10-ppc64le
v5.0.10-s390x
v5.0.10-arm64
v5.0.10
v5.0.11-amd64
v5.0.11-arm64
v5.0.11-s390x
v5.0.11-ppc64le
v5.0.11
```

**Comment by jplimack** [comment]
theres also no release for v5.0.12
https://github.com/minio/operator/releases

**Comment by cesnietor** [comment]
release is still in progress @jplimack, we'll make the release soon.

**Comment by jplimack** [comment]
is it possible to keep the version set in the helm file matching the latest release via a github action? this mismatch is a bit painful for downstream consumers. its also not obvious why this release isnt actually released

**Pull request merged**
