### PR TITLE
Release v4.3.4

### PR DESCRIPTION
**Pull request by dvaldivia**
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Review by Alevsk — DISMISSED** [review]

**Review by bexsoft — APPROVED** [review]

**Comment by donatello** [comment]
You might want to hold-off until minio is released again. The version in this PR has some bugs.

**Comment by dvaldivia** [comment]
@donatello perfect, we can wait for MinIO release

**Comment by harshavardhana** [comment]
> @donatello perfect, we can wait for MinIO release

Released @dvaldivia

**Comment by dvaldivia** [comment]
@donatello @harshavardhana @bexsoft @Alevsk updated the PR to use the latest MinIO

**Review by Alevsk — APPROVED** [review]

**Review by donatello — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
