### PR TITLE
feat: readonly console

### LINKED ISSUE #1905: Operator Console in Read-Only mode
**Is your feature request related to a problem? Please describe.**

By mistake (trying to delete a pool), we deleted a tenant (on a test cluster 🥉).

**Describe the solution you'd like**

We use GitOps (ArgoCD) to create tenants. However, will still use the Operator Console to check configuration and metrics, and connect to MinIO console (this time RW).

Having a global `readonly` flag to the MinIO operator console would avoid this kind of mistake.

**Describe alternatives you've considered**
Disabling the operator console.

**Additional context**

### PR DESCRIPTION
**Pull request by sathieu**
Fixes #1905

### CODE REVIEW

**Review by ramondeklein — APPROVED** [review]
LGTM

**Comment by cniackz** [comment]
I've reviewed this PR, and I find it wonderful how you can manipulate RBAC permissions to grant read-mode access by incorporating fields into the helm chart. I really appreciate this concept and will wait for the tests to pass before approving this PR.

**Review by cniackz — APPROVED** [review]
LGTM

**Comment by cniackz** [comment]
I will await the team's review of this PR, after which we can proceed with the merge.

**Pull request merged**
