### PR TITLE
Release RedHat catalogs v5.0.15

### PR DESCRIPTION
**Pull request by pjuarezd**

### CODE REVIEW

**Comment by pjuarezd** [comment]
Publish to redhat marketplace https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/751

**Comment by pjuarezd** [comment]
Publish to certified Operators https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3853

**Comment by pjuarezd** [comment]
> Publish to redhat marketplace [redhat-openshift-ecosystem/redhat-marketplace-operators#751](https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/751)

This publish is failing, probably a bug in the pipeline, already opened a Suport case https://connect.redhat.com/support/technology-partner/#/case/03812353

**Comment by pjuarezd** [comment]
> > Publish to redhat marketplace [redhat-openshift-ecosystem/redhat-marketplace-operators#751](https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/751)
> 
> This publish is failing, probably a bug in the pipeline, already opened a Suport case https://connect.redhat.com/support/technology-partner/#/case/03812353

Both Catalogs are published!, this PR is ready to be merged

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
