### PR TITLE
support liveness/readinessProbe for completeness

### PR DESCRIPTION
**Pull request by harshavardhana**
we still discourage setting these values,
since they are unexpected for a MinIO deployment
we shall just add this here such that users can
still configure it, our implementations for
readiness and liveness already avoid previous
sideaffects, so this change is harmless.

### CODE REVIEW

**Comment by ravindk89** [comment]
Q: What is the use case here, where a user *would* want to set these? I don't mind setting and leaving them just in the reference, but it would be good to know for if/when someone implements it and then starts seeing some related behavior (at least for support help)

**Comment by harshavardhana** [comment]
> Q: What is the use case here, where a user _would_ want to set these? I don't mind setting and leaving them just in the reference, but it would be good to know for if/when someone implements it and then starts seeing some related behavior (at least for support help)

No usecase just for completeness @ravindk89

**Comment by Alevsk** [comment]
@harshavardhana do we want to add `liveness/readinessProbe` for all other services? kes, postgres, logsearch, prometheus, etc?

**Comment by harshavardhana** [comment]
> @harshavardhana do we want to add `liveness/readinessProbe` for all other services? kes, postgres, logsearch, prometheus, etc?

No this is for tenant spec alone

**Review by Alevsk — APPROVED** [review]

**Review by dvaldivia — APPROVED** [review]

**Pull request merged**
