### PR TITLE
update PV messaging

### PR DESCRIPTION
**Pull request by nitisht**

### CODE REVIEW

**Comment by abperiasamy** [comment]
Since MinIO has built-in erasure-code support for high-availability and data protection, we recommend the following CSI drivers for high-performance and scale:
-  [Local PV](https://kubernetes.io/docs/concepts/storage/volumes/#local)
-  [vSAN Direct](https://www.vmware.com/products/vsan.html)
-  [OpenEBS Local PV](https://docs.openebs.io/docs/next/localpv.html)

**Comment by ravindk89** [comment]
LGTM with AB's recommendations. maybe "scale" -> "scalability" 

Also wondering if we should explicitly warn against using network-attached PV, such as NFS or a cloud provider-backed volume. Maybe something like "MinIO recommends *against* Persistent Volume drivers or plugins which use network-attached storage, as network latency reduces performance compared to locally-attached disks."

**Comment by harshavardhana** [comment]
> Also wondering if we should explicitly warn against using network-attached PV, such as NFS or a cloud provider-backed volume. Maybe something like "MinIO recommends _against_ Persistent Volume drivers or plugins which use network-attached storage, as network latency reduces performance compared to locally-attached disks."

Yes, we should @ravindk89 especially NFS being used with MinIO distributed setup.

**Comment by nitisht** [comment]
Addressed the comments, PTAL @kannappanr @ravindk89

**Comment by ravindk89** [comment]
LGTM

**Review by ravindk89 — APPROVED** [review]

**Pull request merged**
