### PR TITLE
Add link to generated CRD doc

### PR DESCRIPTION
**Pull request by upodroid**
Fixes: https://github.com/minio/operator/issues/432

### CODE REVIEW

**Comment by ravindk89** [comment]
@harshavardhana @dvaldivia there was a discussion a while back about reducing the size of the CRD by removing some descriptor fields. Is that still a concern, where the generated docs might be inaccurate (or partial)?

**Comment by harshavardhana** [comment]
> @harshavardhana @dvaldivia there was a discussion a while back about reducing the size of the CRD by removing some descriptor fields. Is that still a concern, where the generated docs might be inaccurate (or partial)?

There doesn't seem to be the case, I have generated with the CRDs in master @ravindk89 and they seem to generate fine.

**Comment by dvaldivia** [comment]
@harshavardhana yes it's still a concern, the kubernetes API will reject the CRD if it's too large which happens with the two versions in a single CRD￼

**Comment by harshavardhana** [comment]
> @harshavardhana yes it's still a concern, the kubernetes API will reject the CRD if it's too large which happens with the two versions in a single CRD￼

does it still happen? @dvaldivia

**Comment by dvaldivia** [comment]
@harshavardhana yes if we add the descriptions

**Comment by harshavardhana** [comment]
> @harshavardhana yes if we add the descriptions

the crd.adoc is generated with whatever crd is in master - I am assuming this issue is handled in master @dvaldivia

**Comment by ravindk89** [comment]
So based on @dvaldivia 's post, my assumption here is that *eventually* the CRD generation will not include the description fields, because we intend to (or already have) removed them. 

We might still be able to use the CRD generation as just high-level fields. I can parse the adoc and compare it to what I've already documented so I can at least track changes to the CRD as they come. That way we can try to mix a best-of-two-worlds approach, with programmatic generation of the skeleton, but comprehensive reference docs that don't bog down the CRD size. 

Thoughts @harshavardhana @dvaldivia

**Comment by harshavardhana** [comment]
> So based on @dvaldivia 's post, my assumption here is that _eventually_ the CRD generation will not include the description fields, because we intend to (or already have) removed them.
> 
> We might still be able to use the CRD generation as just high-level fields. I can parse the adoc and compare it to what I've already documented so I can at least track changes to the CRD as they come. That way we can try to mix a best-of-two-worlds approach, with programmatic generation of the skeleton, but comprehensive reference docs that don't bog down the CRD size.
> 
> Thoughts @harshavardhana @dvaldivia

if we haven't removed them - can we remove them?

**Comment by ravindk89** [comment]
@harshavardhana https://github.com/minio/operator/blob/master/resources/base/crds/minio.min.io_tenants.yaml the desc fields are already removed in master from what i can see

**Comment by harshavardhana** [comment]
> @harshavardhana https://github.com/minio/operator/blob/master/resources/base/crds/minio.min.io_tenants.yaml the desc fields are already removed in master from what i can see

Then generating doc is fine @ravindk89 its automatically able to add generic descriptions

**Comment by nitisht** [comment]
Can we take this @ravindk89 @harshavardhana @dvaldivia

**Comment by ravindk89** [comment]
Yeah @nitisht I think we're OK. My big action item is to migrate the independent work I've done on documenting these fields into the code base so the autogenerated CRD has more useful details. This will take time, but in the short term linking to the generated docs is still our route forward.

**Review by ravindk89 — APPROVED** [review]

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
