### PR TITLE
Add support to Freeze tenant

### PR DESCRIPTION
**Pull request by dvaldivia**
Adds support to freeze a tenant via the `tenant.spec.freeze = true` field which is optional. if `freeze=true` then we will remove all pods and report the tenant state as `Frozen` upon changing the field to `freeze=false` or removing it from the definition, the pods are returned.

To test this, deploy any tenant and wait for it to be ready, then add field `freeze: true` to the `tenant.spec`

I also re-structured some code from `main-controller.go` into their own files, mainly code used to check the state of prometheus and log search.

Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>

### CODE REVIEW

**Comment by harshavardhana** [comment]
Do not understand what is this useful for?

**Comment by dvaldivia** [comment]
@harshavardhana we've discussed this before, it's a way to "Turn Off" tenants, it simply removes any pods without the need to delete the tenant to achieve the same.

**Comment by harshavardhana** [comment]
> @harshavardhana we've discussed this before, it's a way to "Turn Off" tenants, it simply removes any pods without the need to delete the tenant to achieve the same.

Is unfreeze also allowed? I am unable to understand the purpose of this feature.

**Comment by dvaldivia** [comment]
@harshavardhana yes! you can freeze a tenant to get rid of it's pods (similar to scaling deployments and statefulsets to 0) and then unfreeze it to restore it to normal operation

**Comment by dvaldivia** [comment]
@harshavardhana this will also allow us to require users to "shut down" the instance before deleting it, making it even harder to accidentally delete any tenant

**Comment by harshavardhana** [comment]
PTAL at the conflicts @dvaldivia

**Comment by harshavardhana** [comment]
> Adds support to freeze a tenant via the `tenant.spec.freeze = true` field which is optional. if `freeze=true` then we will remove all pods and report the tenant state as `Frozen` upon changing the field to `freeze=false` or removing it from the definition, the pods are returned.

I think removing pods is a bad idea, instead, we will bring in I/O suspend feature on MinIO as an `admin API` if called will suspend all incoming I/O while completing any ongoing transactions. 

this API can be used to toggle "resume" functionality as well, all without doing any pod recycling etc.

**Comment by harshavardhana** [comment]
this PR is not needed https://github.com/minio/minio/pull/13707 - server allows now freezing tenants using `mc admin service freeze`  @dvaldivia

**Pull request closed without merging**
